insert into product (name, brand, made_in, price) values ('W126', 'Mercedes-Benz', 'Portugal', 6726.71);
insert into product (name, brand, made_in, price) values ('57', 'Maybach', 'Colombia', 6181.61);
insert into product (name, brand, made_in, price) values ('325', 'BMW', 'Indonesia', 8839.51);
insert into product (name, brand, made_in, price) values ('DBS', 'Aston Martin', 'Iran', 2715.29);
insert into product (name, brand, made_in, price) values ('Firebird', 'Pontiac', 'Portugal', 7978.78);
insert into product (name, brand, made_in, price) values ('Entourage', 'Hyundai', 'Indonesia', 1946.92);
insert into product (name, brand, made_in, price) values ('Cougar', 'Mercury', 'Greece', 6062.7);
insert into product (name, brand, made_in, price) values ('G37', 'Infiniti', 'China', 5340.52);
insert into product (name, brand, made_in, price) values ('Savana 1500', 'GMC', 'Portugal', 2008.59);
insert into product (name, brand, made_in, price) values ('530', 'BMW', 'Wallis and Futuna', 8615.73);
insert into product (name, brand, made_in, price) values ('Accent', 'Hyundai', 'Nigeria', 3546.48);
insert into product (name, brand, made_in, price) values ('Safari', 'Pontiac', 'Vietnam', 7303.74);
insert into product (name, brand, made_in, price) values ('M3', 'BMW', 'China', 9478.82);
insert into product (name, brand, made_in, price) values ('RX', 'Lexus', 'Ireland', 8347.24);
insert into product (name, brand, made_in, price) values ('Laser', 'Ford', 'Peru', 6617.06);
insert into product (name, brand, made_in, price) values ('Sierra 3500', 'GMC', 'China', 7846.04);
insert into product (name, brand, made_in, price) values ('V40', 'Volvo', 'Portugal', 8260.96);
insert into product (name, brand, made_in, price) values ('A8', 'Audi', 'Colombia', 7793.18);
insert into product (name, brand, made_in, price) values ('Ciera', 'Oldsmobile', 'Russia', 1066.73);
insert into product (name, brand, made_in, price) values ('SLK-Class', 'Mercedes-Benz', 'Indonesia', 8143.32);
insert into product (name, brand, made_in, price) values ('Continental', 'Lincoln', 'Mozambique', 1103.78);
insert into product (name, brand, made_in, price) values ('E-Series', 'Ford', 'Philippines', 5981.84);
insert into product (name, brand, made_in, price) values ('Defender 90', 'Land Rover', 'China', 5740.57);
insert into product (name, brand, made_in, price) values ('Explorer', 'Ford', 'Oman', 2346.85);
insert into product (name, brand, made_in, price) values ('Explorer', 'Ford', 'Poland', 6790.55);
insert into product (name, brand, made_in, price) values ('Corolla', 'Toyota', 'Libya', 5702.69);
insert into product (name, brand, made_in, price) values ('Charger', 'Dodge', 'Philippines', 8552.86);
insert into product (name, brand, made_in, price) values ('XK', 'Jaguar', 'Angola', 9476.17);
insert into product (name, brand, made_in, price) values ('5 Series', 'BMW', 'China', 2255.67);
insert into product (name, brand, made_in, price) values ('2500 Club Coupe', 'GMC', 'Netherlands', 9584.57);
insert into product (name, brand, made_in, price) values ('Vitara', 'Suzuki', 'Russia', 8022.07);
insert into product (name, brand, made_in, price) values ('LR2', 'Land Rover', 'Sri Lanka', 9754.9);
insert into product (name, brand, made_in, price) values ('Highlander', 'Toyota', 'Indonesia', 9550.99);
insert into product (name, brand, made_in, price) values ('G', 'Infiniti', 'Poland', 4146.74);
insert into product (name, brand, made_in, price) values ('ES', 'Lexus', 'Indonesia', 4388.41);
insert into product (name, brand, made_in, price) values ('Cayman', 'Porsche', 'Czech Republic', 8271.56);
insert into product (name, brand, made_in, price) values ('Navigator', 'Lincoln', 'Ukraine', 8540.79);
insert into product (name, brand, made_in, price) values ('Fiesta', 'Ford', 'Luxembourg', 4949.23);
insert into product (name, brand, made_in, price) values ('Murano', 'Nissan', 'Ukraine', 3569.53);
insert into product (name, brand, made_in, price) values ('Stealth', 'Dodge', 'Myanmar', 7066.8);
insert into product (name, brand, made_in, price) values ('RL', 'Acura', 'Indonesia', 8400.25);
insert into product (name, brand, made_in, price) values ('Sephia', 'Kia', 'France', 2497.4);
insert into product (name, brand, made_in, price) values ('Silverado 3500', 'Chevrolet', 'Indonesia', 3169.04);
insert into product (name, brand, made_in, price) values ('Civic', 'Honda', 'Germany', 9756.57);
insert into product (name, brand, made_in, price) values ('Altima', 'Nissan', 'Cuba', 9775.42);
insert into product (name, brand, made_in, price) values ('Baja', 'Subaru', 'Croatia', 1209.97);
insert into product (name, brand, made_in, price) values ('Avalon', 'Toyota', 'Afghanistan', 1153.48);
insert into product (name, brand, made_in, price) values ('Expedition', 'Ford', 'Mexico', 7610.98);
insert into product (name, brand, made_in, price) values ('Justy', 'Subaru', 'Indonesia', 4689.92);
insert into product (name, brand, made_in, price) values ('Riviera', 'Buick', 'Portugal', 4893.22);
insert into product (name, brand, made_in, price) values ('Jetta', 'Volkswagen', 'Poland', 4610.03);
insert into product (name, brand, made_in, price) values ('Yukon', 'GMC', 'China', 9307.03);
insert into product (name, brand, made_in, price) values ('Suburban 2500', 'Chevrolet', 'France', 2731.66);
insert into product (name, brand, made_in, price) values ('Odyssey', 'Honda', 'Russia', 3033.14);
insert into product (name, brand, made_in, price) values ('Gran Sport', 'Maserati', 'Indonesia', 7590.13);
insert into product (name, brand, made_in, price) values ('Miata MX-5', 'Mazda', 'China', 3778.93);
insert into product (name, brand, made_in, price) values ('Z4', 'BMW', 'Dominican Republic', 2805.59);
insert into product (name, brand, made_in, price) values ('Discovery', 'Land Rover', 'France', 3056.37);
insert into product (name, brand, made_in, price) values ('612 Scaglietti', 'Ferrari', 'Indonesia', 3630.98);
insert into product (name, brand, made_in, price) values ('E-Series', 'Ford', 'China', 9608.39);
insert into product (name, brand, made_in, price) values ('LaCrosse', 'Buick', 'Philippines', 4925.43);
insert into product (name, brand, made_in, price) values ('F-Series', 'Ford', 'Czech Republic', 4589.46);
insert into product (name, brand, made_in, price) values ('G5', 'Pontiac', 'Brazil', 1292.76);
insert into product (name, brand, made_in, price) values ('Milan', 'Mercury', 'Canada', 9860.09);
insert into product (name, brand, made_in, price) values ('Civic', 'Honda', 'Indonesia', 6247.3);
insert into product (name, brand, made_in, price) values ('RX Hybrid', 'Lexus', 'China', 1395.57);
insert into product (name, brand, made_in, price) values ('Mustang', 'Ford', 'Brazil', 6617.18);
insert into product (name, brand, made_in, price) values ('Altima', 'Nissan', 'Nigeria', 7622.24);
insert into product (name, brand, made_in, price) values ('Rabbit', 'Volkswagen', 'China', 9344.72);
insert into product (name, brand, made_in, price) values ('XK Series', 'Jaguar', 'Mongolia', 1998.0);
insert into product (name, brand, made_in, price) values ('Avalon', 'Toyota', 'Poland', 6234.43);
insert into product (name, brand, made_in, price) values ('X6', 'BMW', 'Brazil', 5293.24);
insert into product (name, brand, made_in, price) values ('929', 'Mazda', 'Mexico', 9799.17);
insert into product (name, brand, made_in, price) values ('Corvette', 'Chevrolet', 'Ivory Coast', 4966.73);
insert into product (name, brand, made_in, price) values ('X5 M', 'BMW', 'China', 9323.34);
insert into product (name, brand, made_in, price) values ('Baja', 'Subaru', 'China', 7344.88);
insert into product (name, brand, made_in, price) values ('2500', 'Chevrolet', 'China', 5986.83);
insert into product (name, brand, made_in, price) values ('Trooper', 'Isuzu', 'Poland', 7000.71);
insert into product (name, brand, made_in, price) values ('XC90', 'Volvo', 'Indonesia', 2626.92);
insert into product (name, brand, made_in, price) values ('B-Series Plus', 'Mazda', 'China', 5896.05);
insert into product (name, brand, made_in, price) values ('SC', 'Lexus', 'Thailand', 7781.49);
insert into product (name, brand, made_in, price) values ('GTO', 'Pontiac', 'China', 1560.95);
insert into product (name, brand, made_in, price) values ('Chariot', 'Mitsubishi', 'Afghanistan', 3929.99);
insert into product (name, brand, made_in, price) values ('B-Series Plus', 'Mazda', 'United States', 8863.41);
insert into product (name, brand, made_in, price) values ('Prowler', 'Chrysler', 'Mongolia', 6311.38);
insert into product (name, brand, made_in, price) values ('S4', 'Audi', 'Japan', 9003.65);
insert into product (name, brand, made_in, price) values ('GTO', 'Pontiac', 'Indonesia', 9821.62);
insert into product (name, brand, made_in, price) values ('E-Series', 'Ford', 'China', 4410.24);
insert into product (name, brand, made_in, price) values ('SC', 'Lexus', 'China', 8813.14);
insert into product (name, brand, made_in, price) values ('TT', 'Audi', 'Philippines', 7459.0);
insert into product (name, brand, made_in, price) values ('Sonata', 'Hyundai', 'China', 3944.29);
insert into product (name, brand, made_in, price) values ('LS', 'Lincoln', 'Philippines', 5317.12);
insert into product (name, brand, made_in, price) values ('Yukon XL 2500', 'GMC', 'Indonesia', 5843.54);
insert into product (name, brand, made_in, price) values ('Previa', 'Toyota', 'Philippines', 1037.35);
insert into product (name, brand, made_in, price) values ('Montero', 'Mitsubishi', 'Colombia', 1413.72);
insert into product (name, brand, made_in, price) values ('Sidekick', 'Suzuki', 'Greece', 2262.54);
insert into product (name, brand, made_in, price) values ('Esperante', 'Panoz', 'France', 3325.64);
insert into product (name, brand, made_in, price) values ('Bronco', 'Ford', 'United States', 5375.11);
insert into product (name, brand, made_in, price) values ('Brat', 'Subaru', 'China', 9986.9);
insert into product (name, brand, made_in, price) values ('Caravan', 'Dodge', 'Indonesia', 4954.06);
